/*************************************************************************
    > File Name: params.h
    > Author: xlzh
    > Mail: xiaolongzhang2015@163.com
    > Created Time: 2025年12月05 18时15分26秒
 ************************************************************************/

#ifndef INSDCXMLPARSER_PARAMS_H
#define INSDCXMLPARSER_PARAMS_H


/* chose the mode to decide operation */
enum ParamsMode {
    PARAMS_INVALID=0,
    PARAMS_BUILD=1,
    PARAMS_SAMPLE = 2,
    PARAMS_PROJECT = 3
};


/*! @typedef args_t
  @abstract structure for the command line args
  @field help                [0|1] 1: print the help information
  @field params_mode         the parameters mode, refer to PARAMS_MODE
  @field xml_date            the xml_file released date (e.g. 20251205)
  @field xml_file            the NCBI released xml file (e.g. biosample_set.xml)
  @field xml_type            the type of the xml file, only could be SAMPLE or PROJECT
  @field database            the database name generated by xml_file (e.g. biosample.db)
  @field output_dir          the output directory, which only used in comparing operation
*/
typedef struct args_t {
    int help;
    int params_mode;
    int xml_date;
    char *xml_file;
    char *xml_type;
    char *database;
    char *output_dir;
} args_t;


/*! @function: parse the command line parameters
  @param  argc        the number of args from command line
  @param  argv        the parameters provided by user
  @return             the parsed args (memory has been allocated)
 */
args_t *params_parse(int argc, char **argv);


#endif //INSDCXMLPARSER_PARAMS_H